version: '3'
networks:
  app-web:
    driver: bridge
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-web
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-web
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime
  backend:
    image: yjj603/backend-pkg1
    ports:
      - "4008:4008"
    depends_on:
      - mysql
      - redis
    networks:
      - app-web
  frontend:
    image: yjj603/client-pkg1
    ports:
      - "4001:80"
    depends_on:
      - backend
