name: monorepo-template
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false
      - name: build
        run: |
          pnpm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
          pnpm -F utils-common install
          pnpm -F client install
          pnpm -F client run build
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./client/apps/pkg1
          file: ./client/apps/pkg1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/client-pkg1:latest
      - name: SSH
        uses: fifsky/ssh-action@master
        with:
          command: | 
            client/apps/pkg1/start.sh
          host: 49.234.37.125
          user: root
          pass: yjj603YJJ063



